### ISSUE TITLE
wifibroot import errors

### ISSUE THREAD

**Issue by ihateadmins** [hash3liZer/WiFiBroot#12]
Hello, i followed the instructions/documentation and when trying to run wifibroot i am getting ImportErrors:
Traceback (most recent call last):
  File "wifibroot.py", line 19, in <module>
    from wireless import Shifter
  File "/usr/local/bin/WiFiBroot/wireless/__init__.py", line 3, in <module>
    from wireless.cracker import PSK
  File "/usr/local/bin/WiFiBroot/wireless/cracker.py", line 6, in <module>
    from pbkdf2 import PBKDF2
ImportError: No module named pbkdf2

I don't know much about python so it might be due to "from wireless ..." being a folder and not a file. I wanted to see if there are any other errors so i tried to replace all files in the same directory and edit the wifibroot.py and exclude the missing files/classes like:
psk, eAPoL, pmkid, capture_pmkid, capture_hand, deauth
Excluding these wifibroot will "run" without errors, but surely will make it not functioning

I am running the newest kali linux with scapy 2.4.0 and tried python, python2, python2.7, python3, python3.7. Running it on python3 versions will result in SyntaxError at line 197

I hope you can help.
Thanks in advance

**Comment by ihateadmins** [comment]
sorry, i didn't see the other threads. You already wrote the solution:
pip install pbkdf2

thanks!
