### ISSUE TITLE
 No buffer space available

### ISSUE THREAD

**Issue by 3nboos** [hash3liZer/WiFiBroot#14]
Exception in thread T Shooter:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/WiFiBroot/wireless/sniper.py", line 181, in shoot
    sendp(__pkt_to_cl, iface=self.iface, count=1, verbose=False)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 315, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 276, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 551, in send
    return SuperSocket.send(self, x)
  File "/usr/lib/python2.7/dist-packages/scapy/supersocket.py", line 45, in send
    return self.outs.send(sx)
error: [Errno 105] No buffer space available

[^] 32-> 240A64E75E3E (AzureWave) >< F81897824E61 (2Wire,) [Deauthentication]
Exception in thread T Shooter:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/WiFiBroot/wireless/sniper.py", line 181, in shoot
    sendp(__pkt_to_cl, iface=self.iface, count=1, verbose=False)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 315, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 276, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 551, in send
    return SuperSocket.send(self, x)
  File "/usr/lib/python2.7/dist-packages/scapy/supersocket.py", line 45, in send
    return self.outs.send(sx)
error: [Errno 105] No buffer space available

**Comment by 3nboos** [comment]
thats the most funny error ever : No buffer space available i got 1 TB, terminal was not loaded
