### ISSUE TITLE
WiFiBroot doesn't boot in Kali Linux (most recent release and update)

### ISSUE THREAD

**Issue by TehBear** [hash3liZer/WiFiBroot#25]
I am running Kali under VM ware. Kali has been updated and I have installed the most recent scapy. I even attempted old fixes under the issues area. 
I've also ensured I had the other dependency I could find.
 apt-get install python-pbkdf2

**This is the feedback I get from each boot** 

root@tehbear:~/WiFiBroot# python wifibroot.py -h
Traceback (most recent call last):
  File "wifibroot.py", line 20, in <module>
    from wireless import Shifter
  File "/root/WiFiBroot/wireless/__init__.py", line 2, in <module>
    from wireless.sniper import Sniper
  File "/root/WiFiBroot/wireless/sniper.py", line 7, in <module>
    from scapy.layers.dot11 import Raw
ImportError: cannot import name Raw

How do I fix this? I have had this on other installations of Kali, I just don't know why it doesn't work now.

**Comment by 5l1v3r1** [comment]
it is about scapy pip3 install scapy==2.4.0, the mentor mentioned.

**Comment by trinitronx** [comment]
This tool [appears to be stagnant][1] & suffering [bit-rot][2].  No updates to `scapy` version since `v2.4.0`, updates were discussed in #8 but it never was completed.  They suggest pinning `scapy` to `2.4.0`, but that version doesn't work on macOS so no luck there.  You may have better luck on Kali.

[1]: https://github.com/hash3liZer/WiFiBroot/graphs/code-frequency
[2]: https://en.wikipedia.org/wiki/Software_rot
