### ISSUE TITLE
ImportError: No module named pbkdf2 on debian buster

### ISSUE THREAD

**Issue by salahmak** [hash3liZer/WiFiBroot#30]
i've cloned the repo, installed scapy with the required version, did everything right, but when i run wifibroot.py it logs this error:
```
Traceback (most recent call last):
  File "wifibroot.py", line 19, in <module>
    from wireless import Shifter
  File "/home/<username>/WiFiBroot/wireless/__init__.py", line 3, in <module>
    from wireless.cracker import PSK
  File "/home/<username>/WiFiBroot/wireless/cracker.py", line 6, in <module>
    from pbkdf2 import PBKDF2
ImportError: No module named pbkdf2
```

**Comment by hash3liZer** [comment]
Just do: 
```
$ pip install pbkdf2
```
