### ISSUE TITLE
ImportError: No module named scapy.all

### ISSUE THREAD

**Issue by dodoaska** [hash3liZer/WiFiBroot#40]
python wifibroot.py --mode 2 -i wlan1mon --verbose -d handshakes -w pmkid.txt          127 ⨯
Traceback (most recent call last):
  File "wifibroot.py", line 17, in <module>
    from screen import Display
  File "/home/asus/WiFiBroot/screen.py", line 2, in <module>
    from scapy.all import *
ImportError: No module named scapy.all

I use kali

**Comment by hash3liZer** [comment]
Install scapy before running: 

```
$ pip install scapy==2.4.0
```

**Comment by dodoaska** [comment]
i will reinstall the kali again
