### ISSUE TITLE
Error: "ImportError: No module named scapy.utils"

### ISSUE THREAD

**Issue by IdrisBouar** [hash3liZer/WiFiBroot#42]
Hello, 
I get prompted with this error when using 'python2':

```
Traceback (most recent call last):
  File "wifibroot.py", line 17, in <module>
    from screen import Display
  File "/home/davinci/tools/WiFiBroot/screen.py", line 2, in <module>
    from scapy.utils import hexdump
ImportError: No module named scapy.utils
```

**Comment by elon30** [comment]
install scapy.utils , i think by [ pip install scapy.utils ]
