### ISSUE TITLE
cannot use

### ISSUE THREAD

**Issue by afasdfsfdsagddafh** [hash3liZer/WiFiBroot#43]
File "/data/data/com.termux/files/home/WiFiBroot/wifibroot.py", line 197
    print "\n"+tabulate(tabulator__, headers=__HEADERS)+"\n"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by Divide-By-0** [comment]
You have to run with python2.7 to get past this, but then you get
```
WiFiBroot/wireless/sniper.py", line 7, in <module>
    from scapy.layers.dot11 import Raw
ImportError: cannot import name Raw
```

When you get rid of these lines, you get
```
python2 wifibroot.py -h  
Traceback (most recent call last):
  File "wifibroot.py", line 19, in <module>
    from wireless import Shifter
  File "~/WiFiBroot/wireless/__init__.py", line 1, in <module>
    from wireless.shifter import Shifter
  File "~/WiFiBroot/wireless/shifter.py", line 3, in <module>
    from scapy.layers.dot11 import Dot11Beacon
  File "~/.pyenv/versions/py27/lib/python2.7/site-packages/scapy/layers/dot11.py", line 19, in <module>
    from scapy.ansmachine import *
  File "~/.pyenv/versions/py27/lib/python2.7/site-packages/scapy/ansmachine.py", line 16, in <module>
    from scapy.sendrecv import send,sendp,sniff
  File "~/.pyenv/versions/py27/lib/python2.7/site-packages/scapy/sendrecv.py", line 32, in <module>
    import scapy.route
  File "~/.pyenv/versions/py27/lib/python2.7/site-packages/scapy/route.py", line 191, in <module>
    conf.route=Route()
  File "~/.pyenv/versions/py27/lib/python2.7/site-packages/scapy/route.py", line 27, in __init__
    self.resync()
  File "~/.pyenv/versions/py27/lib/python2.7/site-packages/scapy/route.py", line 36, in resync
    self.routes = read_routes()
  File "~/.pyenv/versions/py27/lib/python2.7/site-packages/scapy/arch/unix.py", line 82, in read_routes
    netif = rt[4 + mtu_present + prio_present + refs_present + locked]
IndexError: list index out of range
```
So then I ran with `https://github.com/kimocoder/WiFiBroot` instead, used Python 3.11, and did `pip install --upgrade scapy` to get scapy 2.5.0 (as before 2.4.3, you get the above error).

Then I get a MacOS specific error:
```
WiFiBroot/wifibroot.py", line 78, in list_ifaces
    dev = open('/proc/net/dev', 'r')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/proc/net/dev'
```
